# Generated by Django 4.0.5 on 2022-06-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=20, unique=True)),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('balance', models.FloatField(default=0.0)),
                ('coin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinapp.coin')),
            ],
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=200)),
                ('receiver_id', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('operation_date', models.DateTimeField()),
                ('coin_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coinapp.coin')),
            ],
        ),
    ]
