# Generated by Django 4.0.5 on 2022-06-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinapp', '0004_alter_registry_coin_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='coin_used',
            field=models.CharField(max_length=20),
        ),
    ]
